Update README to include examples from Apollo Federation docs
DivvyPayHQ/absinthe_federation pull request #100
Opened 2024-07-08 17:45 UTC by benjaminkimball

2024-07-08 18:22 UTC, kzlsakal requested changes
Great updates to the README, thank you for the PR! Left a few comments.

2024-07-08 18:22 UTC, kzlsakal commented on README.md
> +defmodule Products.Schema do
This is a much better examples section 🚀

2024-07-08 18:22 UTC, kzlsakal commented on README.md
> +    field(:price, :int)
nit here: we should probably encourage the `locals_without_parens` style usage that should be imported by the formatter from absinthe by default. so these should be

```elixir
    directive :key, fields: "id"

    # Any subgraph contributing fields MUST defined a resolve reference.
    field :_resolve_reference, :product  do
      resolve fn %{__typename: "Product", id: id} = entity, _info ->
        {:ok, Map.merge(entity, %{name: "ACME Anvil", price: 10000})}
      end
    end

    field :id, non_null(:id)
    field :name, non_null(:string)
    field :price, :int

2024-07-08 18:22 UTC, kzlsakal commented on README.md
> +~~The `:_resolve_reference` version of the `resolve/1` method will receive a 2 arity function. The first argument is an entity representation and the second the `Absinthe.Resolution.t()`.~~
Does this need to be superstriked?

2024-07-08 18:22 UTC, kzlsakal commented on README.md
> +Your `:_resolve_reference` must return one of the follow:
```suggestion
Your `:_resolve_reference` must return one of the following:
```

2024-07-08 18:22 UTC, kzlsakal commented on README.md
> +{:ok, %Product{id: id, ...}}
I think it could technically return `{:ok, nil}` as well.

2024-07-08 18:22 UTC, kzlsakal commented on README.md
> +      url: "https://specs.apollo.dev/federation/v2.0",
We should probably reference the latest spec here, I think it was v2.3.

2024-07-08 18:22 UTC, kzlsakal commented on README.md
> -+ end
We should probably keep this somewhere, just to show supported Federation v2 directives.

2024-07-08 18:22 UTC, kzlsakal commented on README.md
> +    # This subgraph need only resolve the key fields used to reference the entity.
```suggestion
    # This subgraph only needs to resolve the key fields used to reference the entity.
```

2024-07-08 18:22 UTC, kzlsakal commented on README.md
> +    # Any subgraph contributing fields MUST defined a resolve reference.
```suggestion
    # Any subgraph contributing fields MUST define resolve _resolve_reference.
```

2024-07-08 23:04 UTC, benjaminkimball commented
Oops, should have marked this as a draft! Thanks for the feedback, @kzlsakal. I'll address them as I finish up my clarifications and additions.

2024-07-31 16:21 UTC, kzlsakal requested changes

2024-07-31 16:21 UTC, kzlsakal commented on README.md
> +The following sticks close to the Apollo Federation documentation to better clarify how to achieve the same outcomes with the `Absinthe.Federation` module as you'd get from their JavaScript examples.
Do you mind moving the following note right above the `resolve` call as an in-line code comment in the example? It may not be super clear to mention it right here.

_"Note that implementing the reference resolver with function capture does not work at the moment. Hence, the examples below use an anonymous function."_

2024-07-31 16:21 UTC, kzlsakal commented on README.md
> +    field(:price, :int)
Small nit but the convention to use Absinthe's formatter rules (locals_without_parens) doesn't seem to be reflected here. We could remove the parenthesis from these calls.

2024-07-31 16:21 UTC, kzlsakal commented on README.md
> +      url: "https://specs.apollo.dev/federation/v2.0",
```suggestion
      url: "https://specs.apollo.dev/federation/v2.3",
```
let's reference the latest spec available since we already support it

2024-07-31 16:21 UTC, kzlsakal commented on README.md
> +    # Contributing to an entity does not require it to be otherwise queryable in this subgraph.
Could you elaborate this comment a little bit? How does it relate to the _resolve_reference call below?

2024-07-31 16:21 UTC, kzlsakal commented on README.md
> +            error
Nit: This just seems to be returning the result from the hypothetical find_many function call anyway? If it's just here for posterity, that's fine too, but just wanted to note.

2024-07-31 16:56 UTC, benjaminkimball commented on README.md
> +            error
I'll just simplify it to a faux resolver call.

2024-07-31 16:56 UTC, benjaminkimball commented on README.md
> +    # Contributing to an entity does not require it to be otherwise queryable in this subgraph.
Moved to a leading paragraph and simpler comment with that context.

2024-07-31 19:03 UTC, kzlsakal approved these changes

2024-07-31 20:00 UTC, merged