Rework how entities_field works
DivvyPayHQ/absinthe_federation pull request #104
Opened 2024-12-18 09:52 UTC by maciej-szlosarczyk

Hey 👋 Great work on library!

This is a pretty big PR to address the following points:

- Support Async resolution with 0-arity function
- Support Dataloader.Ecto
- Support function capture resolution

The main idea here is to use normal middleware pipeline for each resolved representation instead of looking at what those middlewares actually are. Unfortunately it changes some API examples and tests, but it brings them in-line with how Absinthe works in general. I.e async/2 helper requires the first argument to be a 0-arity function, but for some reason the [tests](https://github.com/DivvyPayHQ/absinthe_federation/compare/main...maciej-szlosarczyk:absinthe_federation:dataloader-ecto?expand=1#diff-1bdc65a4a98d5ee4ac186068237cb7b44e4776276c2f5bfb9506ea1d0307b129R69) used 1-arity.

2024-12-20 17:27 UTC, kzlsakal requested changes
@maciej-szlosarczyk thank you so much for working on this! These are some great changes, and I left a few comments. If you can address those, I'll be happy to run another test suite on my end.

2024-12-20 17:27 UTC, kzlsakal commented on README.md
> +                %{batch: {{:one, Example.Item}, %{}}, item: [item_id: args.item_id]}
seems like we have defined an `ExampleItem` and not `Example.Item`

2024-12-20 17:27 UTC, kzlsakal commented on test/support/example_item.ex
> +defmodule ExampleItem do
Not a huge deal but let's try to match these Example modules; there is an ExampleItem and a Example.Source and it would be nice if they were consistent.

2024-12-21 07:06 UTC, maciej-szlosarczyk commented on lib/absinthe/federation/schema/entities_field.ex
> +  defp call_middleware(fun, res) when is_function(fun, 2) do
Looks like I missed that, thanks for spotting. A new test is [added](https://github.com/DivvyPayHQ/absinthe_federation/pull/104/commits/4e1585c83343f39027c99244db3242ce624b8a77#diff-1d421b1b53bdf5f9a1701e343277cf5a58335e82b183b11eef16b252ca35ec53).

2024-12-21 07:07 UTC, maciej-szlosarczyk commented on test/support/example_item.ex
> +defmodule ExampleItem do
These are now called all Example.Thing.

2024-12-21 07:08 UTC, maciej-szlosarczyk commented on README.md
> +                %{batch: {{:one, Example.Item}, %{}}, item: [item_id: args.item_id]}
The entire readme uses Example.{Schema,Loader,Item}, this should be consistent now.

2024-12-21 07:10 UTC, maciej-szlosarczyk commented
@kzlsakal Thanks for taking a look, I added the functionality and required test. Should be all good now, let me know if you need to rebase all changes into a single commit and I'll do just that.

2024-12-22 04:37 UTC, kzlsakal commented on lib/absinthe/federation/schema/entities_field.ex
> +  defp call_middleware(fun, res) when is_function(fun, 2) do
Thanks for adding this. While running the tests, I ran into some other issue related to it and I'll post it separately.

2024-12-22 04:51 UTC, kzlsakal requested changes

2024-12-22 04:51 UTC, kzlsakal commented on test/support/example_middleware.ex
> +  def call(res, _opts) do
`Absinthe.Middleware.call/2` has the following function spec: 

```elixir
call(Absinthe.Resolution.t(), term) :: Absinthe.Resolution.t()
```

We may want to have only one `call/2` definition in this test middleware and ensure we're not calling it with something other than an `Absinthe.Resolution` struct as the first argument, otherwise it could be a breaking change for many codebases that expect what Absinthe specifies for it. What do you think?

2024-12-22 04:54 UTC, kzlsakal commented on test/absinthe/federation/schema/entities_field/dataloader_test.exs
> +
```suggestion
```

2024-12-22 04:55 UTC, kzlsakal commented on test/absinthe/federation/schema/entities_field/dataloader_test.exs
> +  # end
```suggestion
```

2024-12-23 14:07 UTC, maciej-szlosarczyk commented on test/support/example_middleware.ex
> +  def call(res, _opts) do
I don't think there's a need for this in this specific middleware, but I made some [extra adjustments](https://github.com/DivvyPayHQ/absinthe_federation/pull/104/commits/be4f6fbb7fa16db0d50b2bcf29f6846fe0224f03) to make sure we are always creating Absinthe.Resolution structs and now passing around field blueprints.

2024-12-24 18:04 UTC, kzlsakal commented on test/support/example_middleware.ex
> +  def call(res, _opts) do
brilliant, exactly what's needed there, thanks!

2024-12-24 18:09 UTC, kzlsakal commented on lib/absinthe/federation/schema/entities_field.ex
> +      schema: schema,
I think this may be the last thing but I encountered some telemetry-related test errors in one of our codebases because these fields were missing on the resolution at the end. I didn't check what else can be taken from the resolution_acc and placed on the resolution we return here, but adding these two satisfied the test suite I was running. Also feel free to grab these in the pattern-match you added above if that's your preference.

```suggestion
      definition: resolution_acc.definition,
      parent_type: resolution_acc.parent_type,
      schema: schema,
```

2024-12-29 19:18 UTC, kzlsakal approved these changes
Thank you very much for your contribution @maciej-szlosarczyk!

2024-12-29 19:19 UTC, merged