Support for dataloader and async middlewares
DivvyPayHQ/absinthe_federation pull request #16
Opened 2021-09-14 12:37 UTC by SvenW

I added support for dataloader and async middlewares. Tried to leave the whole resolution part to absinthes internals but I couldn't get it completely running for middlewares unfortunately. This should however fix #12

2021-09-14 20:35 UTC, kdawgwilk commented on lib/absinthe/federation/schema/entities_field.ex
> +  def call(%{state: :unresolved} = res, _args) do
Do we need another `call` for when the state is anything other than `:unresolved`

2021-09-14 20:35 UTC, kdawgwilk commented on mix.exs
> +      {:dataloader, "~> 1.0.9"},
Do we want to make this an optional dependency?  Could surround the new code with `if Code.ensure_compiled(Dataloader) do ...`  Are we okay with making this a strict transitive dep?

2021-09-15 06:15 UTC, SvenW commented on lib/absinthe/federation/schema/entities_field.ex
> +  def call(%{state: :unresolved} = res, _args) do
I added a regular call that just returns the resolution being passed in. Shouldn't be needed since I'm basically doing the whole resolution manually.

2021-09-15 07:07 UTC, SvenW commented on mix.exs
> +      {:dataloader, "~> 1.0.9"},
Hmm, I've tried to wrap it up in a 
`case Code.ensure_compiled(Dataloader) do
      {:error, _} -> raise "An error....."
      _ -> Do all dataloader parts...
 `
 but it doesn't look great because we get warnings at compile time, like this:
 `
 warning: Dataloader.get_many/4 is undefined (module Dataloader is not available or is yet to be defined)
  lib/absinthe/federation/schema/entities_field.ex:225: Absinthe.Federation.Schema.EntitiesField.call_middleware/2
  `
Not sure what you think though? I would however prefer to keep the dataloader dependency since it's better to use it in the _entities case. It's a matter of performance when doing all _entities queries, since we can bulk load everything better then.

2021-09-15 19:31 UTC, kdawgwilk commented on mix.exs
> +      {:dataloader, "~> 1.0.9"},
I think am okay with this a strict dependency since most absinthe projects will already be including it anyways 👍

2021-09-16 06:29 UTC, SvenW commented
@kdawgwilk Just ping me if you want me to add something else

2021-09-19 05:53 UTC, kdawgwilk commented
Sorry had a hackathon this week so I was mostly heads down, I will take a look at this on Monday

2021-09-20 20:11 UTC, kdawgwilk requested changes

2021-09-20 20:11 UTC, kdawgwilk commented on lib/absinthe/federation/schema/entities_field.ex
> +      Absinthe.Resolution.call(resolution, fun)
We could move this into the `entity_accumulator` possibly to reduce iterations through the list

2021-09-20 20:11 UTC, kdawgwilk commented on lib/absinthe/federation/schema/entities_field.ex
> +    {:ok, res} = fun.(args)
If the resolver returns an error this will raise a MatchError

2021-09-20 20:11 UTC, kdawgwilk commented on lib/absinthe/federation/schema/entities_field.ex
> +    loader = Dataloader.load_many(loader, source, %{__typename: typename}, ids)
```suggestion
    loader
      |> Dataloader.load_many(source, %{__typename: typename}, ids)
      |> Dataloader.run()
      |> Dataloader.get_many(source, %{__typename: typename}, ids)
      |> Enum.map(fn {_, data} -> data end)
```
You will need to remove the lines below as well with this change

2021-09-20 20:11 UTC, kdawgwilk commented on lib/absinthe/federation/schema/entities_field.ex
> +  defp call_middleware({Absinthe.Middleware.Dataloader, {loader, _fun}}, res) do
```suggestion
  defp call_middleware({Absinthe.Middleware.Dataloader, {loader, _fun}}, %{arguments: %{representations: args}}) do
```
This could remove the `get_in` and then you may need another pattern match below for when this fails to handle it gracefully

2021-09-21 08:39 UTC, SvenW commented on lib/absinthe/federation/schema/entities_field.ex
> +          {Absinthe.Middleware.Dataloader, {loader, _fun}} ->
Since it's basically just the resolution function being called I'd say so yes. We've tested it for a week in our staging env and nothing has come up so far.

2021-09-21 08:50 UTC, SvenW commented on lib/absinthe/federation/schema/entities_field.ex
> +  defp call_middleware({Absinthe.Middleware.Dataloader, {loader, _fun}}, res) do
We will always get arguments here and the `representations` key should always be present since otherwise the validation of the query should pick it up

2021-09-22 19:45 UTC, kdawgwilk approved these changes

2021-09-22 19:49 UTC, ewolfmsla approved these changes

2021-09-22 19:59 UTC, ewolfmsla approved these changes

2021-09-22 20:03 UTC, merged

2021-09-22 20:03 UTC, kdawgwilk commented
@SvenW Thank you so much for your contribution! ❤️