Add nested keys support
DivvyPayHQ/absinthe_federation pull request #34
Opened 2021-12-08 09:30 UTC by scottming

The idea is stolen from here: atomic_map/atomic_map.ex at master · ruby2elixir/atomic_map
https://github.com/ruby2elixir/atomic_map/blob/master/lib/atomic_map.ex

2021-12-08 17:26 UTC, kdawgwilk requested changes

2021-12-08 17:26 UTC, kdawgwilk commented on lib/absinthe/federation/schema/entities_field.ex
> +  defp convert_key(k) do
```suggestion
  defp convert_key(k), do: String.to_atom(k)
```

2021-12-08 17:26 UTC, kdawgwilk commented on lib/absinthe/federation/schema/entities_field.ex
> +  defp convert_key_to_atom(v) do
```suggestion
  defp convert_key_to_atom(v), do: v
```

2021-12-08 17:26 UTC, kdawgwilk commented on lib/absinthe/federation/schema/entities_field.ex
> +      k = k |> convert_key()
prefer passing the arg without a pipe when there is only one pipe
```suggestion
      k = convert_key(k)
```

2021-12-08 17:26 UTC, kdawgwilk commented on lib/absinthe/federation/schema/entities_field.ex
> +      v = v |> convert_key_to_atom()
```suggestion
      v = convert_key_to_atom(v)
```

2021-12-08 17:26 UTC, kdawgwilk commented on lib/absinthe/federation/schema/entities_field.ex
> +  defp convert_key_to_atom(map) when is_map(map) do
plural makes a bit more sense to me since it is recursive
```suggestion
  defp convert_keys_to_atom(map) when is_map(map) do
```

2021-12-09 02:47 UTC, scottming commented on lib/absinthe/federation/schema/entities_field.ex
> +  defp convert_key_to_atom(map) when is_map(map) do
it makes sense

2021-12-09 02:51 UTC, scottming commented on lib/absinthe/federation/schema/entities_field.ex
> +      k = k |> convert_key()
I found you are flowing the credo rules, Do we need to add the `credo` deps in [:dev, : test]?

2021-12-09 05:37 UTC, kdawgwilk approved these changes

2021-12-14 21:20 UTC, kdawgwilk requested changes

2021-12-14 21:20 UTC, kdawgwilk commented on lib/absinthe/federation/schema/entities_field.ex
> +      acc |> Map.put(k, v)
```suggestion
      Map.put(acc, k, v)
```

2021-12-14 23:20 UTC, kdawgwilk approved these changes

2021-12-14 23:35 UTC, MrGrinst approved these changes

2021-12-14 23:43 UTC, merged