Support key fields valification
DivvyPayHQ/absinthe_federation pull request #36
Opened 2022-01-08 04:16 UTC by scottming

This pr is part of the section on key_feilds validation, and I was going to go ahead and implement the section on external. But on closer inspection of the main branch of Apollo Federation. I see that they will be removing this type of validation in the future, so I'm not sure if I want to continue.

The error implemented code is [here](https://github.com/apollographql/federation/blob/main/internals-js/src/error.ts)

[erro2.md](https://github.com/DivvyPayHQ/absinthe_federation/files/7832538/erro2.md)

generate command is: `npm run error-code-doc`

If I need to continue with some validation, it would be more appropriate to target both federation1 and 2. Do you have any suggestions on this?

2022-01-10 23:01 UTC, kdawgwilk requested changes

2022-01-10 23:01 UTC, kdawgwilk commented on lib/absinthe/federation/schema/phase/key_fields_must_be_exist.ex
> +    The @key #{inspect(key)} is not exist in #{inspect(object.identifier)} object.
```suggestion
    The @key #{inspect(key)} does not exist in #{inspect(object.identifier)} object.
```

2022-01-10 23:01 UTC, kdawgwilk commented on lib/absinthe/federation/schema/phase/key_fields_must_be_exist.ex
> +    The field #{inspect(field)} of @key #{inspect(key_fields)} is not exist.
```suggestion
    The field #{inspect(field)} of @key #{inspect(key_fields)} does not exist.
```

2022-01-10 23:02 UTC, kdawgwilk commented
federation v2 is still 3-6 months out so we can focus purely on v1 for now

2022-01-11 00:32 UTC, scottming commented
> federation v2 is still 3-6 months out so we can focus purely on v1 for now

Ok, I'll submit another pr for the external thing.

2022-01-12 06:47 UTC, kdawgwilk approved these changes

2022-01-12 17:24 UTC, MrGrinst approved these changes

2022-01-12 20:14 UTC, merged