Fix introspection query failing with "Cannot return null for non-nullable field"
DivvyPayHQ/absinthe_federation pull request #81
Opened 2023-11-02 12:33 UTC by dhrdlicka

Moved type definitions from `Absinthe.Federation.Schema.Prototype` to `Absinthe.Federation.Types`. This fixes introspection queries failing due to the argument types for the `@link` directive not resolving properly as the types would not get imported from the schema prototype.

2023-11-02 16:45 UTC, kdawgwilk approved these changes

2023-11-02 20:26 UTC, kzlsakal requested changes
Thanks for the PR @dhrdlicka!

I tested this on a local subgraph, and introspection on both the GraphiQL Playground and the Apollo Explorer are producing the following error, although the network call returns a successful response:

```
instrument.js:105 Error: Invalid or incomplete schema, unknown type: _FieldSet. Ensure that a full introspection query is used in order to build a client schema.
```

Do we need to omit certain records that refer to this `_FieldSet`? Not sure if this change is causing redundant types to be added to the schema or if they were already there, but it seems like we still cannot produce a successful introspection the way it is.

2023-11-03 14:44 UTC, dhrdlicka commented
@kzlsakal I guess I should have checked the actual query result before coming to premature conclusions 😄

Yeah, the introspection query doesn't crash anymore but the types defined in the schema prototype are still not there. I think they might be getting stripped when they're not actually used in the schema itself.

2023-11-08 11:54 UTC, dhrdlicka commented
Related: absinthe-graphql/absinthe#1279

2024-07-11 13:33 UTC, antonioparisi commented
any update on this?

2024-08-22 11:12 UTC, dhrdlicka commented
Fixed by upstream, closing.

2024-08-22 11:12 UTC, closed without merging