Add `composeDirective` directive, fixes #72
DivvyPayHQ/absinthe_federation pull request #91
Opened 2024-02-08 15:39 UTC by cschiewek

Pretty straight forward addition of the `composeDirective` directive.

I also considered adding a `compose` macro to notation to facilitate expansion, so that the `link` and `composeDirective` would be automatically added to the schema without having to add them to the `extend schema` block:

```
directive :custom do
  compose "https://spec.example.org/custom/v1.0"
  on [:schema]
end
```

I decided against it for this PR, but if that is something y'all think is worth the effort, let me know and I'll create an issue and do it at some point.

Cheers!

2024-02-09 03:24 UTC, kzlsakal commented
@cschiewek thank you for the PR!

>I also considered adding a compose macro to notation to facilitate expansion, so that the link and composeDirective would be automatically added to the schema without having to add them to the extend schema block

This is a very nice idea, although it's fine to support `@composeDirective` without that convenience for now.

2024-02-09 03:25 UTC, kzlsakal requested changes

2024-02-09 03:25 UTC, kzlsakal commented on test/absinthe/federation/notation_test.exs
> +    test "schema with multiple composeDirectives is valiad" do
```suggestion
    test "schema with multiple composeDirectives is valid" do
```
nit

2024-02-09 03:25 UTC, kzlsakal commented on test/absinthe/federation/notation_test.exs
> +          directive :composeDirective, name: "@other"
This might fail the federated composition since we don't have a directive definition for `@other`

2024-02-09 03:25 UTC, kzlsakal commented on test/absinthe/federation/notation_test.exs
> +      assert sdl =~ ~s{schema @composeDirective(name: "@other") @composeDirective(name: "@custom")}
Could you also assert that the `sdl` has the definition of the `@custom` directive as `directive @custom on SCHEMA`? I believe the federated schema composition will fail unless the directives are defined or imported via `@link`.

2024-02-09 06:45 UTC, kzlsakal commented on test/absinthe/federation/notation_test.exs
> +      assert sdl =~ ~s{schema @composeDirective(name: "@other") @composeDirective(name: "@custom")}
I realized that the missing directive definitions are due to the custom prototype approach in #90. I do have a possible solution for this in mind, so it's fine if this test doesn't assert the directive definition on the schema. Feel free to resolve this.

2024-02-12 13:16 UTC, cschiewek commented on test/absinthe/federation/notation_test.exs
> +          directive :composeDirective, name: "@other"
Fixed in [d947721](https://github.com/DivvyPayHQ/absinthe_federation/pull/91/commits/d94772138d18c2a77c769538f7c3c189fc32a114)

2024-02-20 16:49 UTC, kzlsakal approved these changes

2024-02-20 16:49 UTC, merged